manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: mwlaboratories
      url-base: https://github.com/mwlaboratories
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      revision: ac7f75b8

    # zmk module for PS/2 mouse / TP driver
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      # remote: infused-kim
      remote: badjeff
      revision: main
  self:
    path: config
