manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      revision: ac7f75b8

    # Updated fork of infused-kim's initial work
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: badjeff
      revision: 2df4d6d

  self:
    path: config
